package dev.langchain4j.example.entity.browser._browser;

import java.util.Arrays;
import java.util.List;

public final class ChromeConfig {
    // 用户代理配置
    public static final String DEFAULT_USER_AGENT =
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36";

    // 路径配置
    public static final String EXTENSIONS_PATH = "chrome_extensions";
    public static final String PROFILE_PATH = "chrome_profile";
    public static final String PROFILE_USER = "Default";
    public static final int DEBUG_PORT = 9222;

    // 禁用的Chrome组件
    public static final List<String> DISABLED_COMPONENTS = Arrays.asList(
            "Translate",
            "AcceptCHFrame",
            "OptimizationHints",
            "ProcessPerSiteUpToMainFrameThreshold",
            "InterestFeedContentSuggestions",
            "CalculateNativeWinOcclusion",
            "BackForwardCache",
            "HeavyAdPrivacyMitigations",
            "LazyFrameLoading",
            "ImprovedCookieControls",
            "PrivacySandboxSettings4",
            "AutofillServerCommunication",
            "CertificateTransparencyComponentUpdater",
            "DestroyProfileOnBrowserClose",
            "CrashReporting",
            "OverscrollHistoryNavigation",
            "InfiniteSessionRestore"
    );

    // 无头模式参数
    public static final List<String> HEADLESS_ARGS = Arrays.asList(
            "--headless=new",
            "--test-type",
            "--test-type=gpu"
    );

    // Docker专用参数
    public static final List<String> DOCKER_ARGS = Arrays.asList(
            "--no-sandbox",
            "--disable-gpu-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--no-xshm"
    );

    // 安全禁用参数
    public static final List<String> DISABLE_SECURITY_ARGS = Arrays.asList(
            "--disable-web-security",
            "--disable-site-isolation-trials",
            "--disable-features=IsolateOrigins,site-per-process",
            "--allow-running-insecure-content",
            "--ignore-certificate-errors",
            "--ignore-ssl-errors",
            "--ignore-certificate-errors-spki-list",
            "--allow-insecure-localhost"
    );

    // 确定性渲染参数
    public static final List<String> DETERMINISTIC_RENDERING_ARGS = Arrays.asList(
            "--deterministic-mode",
            "--js-flags=--random-seed=1157259159",
            "--force-device-scale-factor=1",
            "--hide-scrollbars",
            "--enable-webgl",
            "--font-render-hinting=none",
            "--force-color-profile=srgb",
            "--disable-partial-raster",
            "--disable-skia-runtime-opts",
            "--disable-2d-canvas-clip-aa",
            "--disable-lazy-loading",
            "--disable-renderer-backgrounding",
            "--disable-background-networking",
            "--disable-background-timer-throttling",
            "--disable-backgrounding-occluded-windows",
            "--disable-ipc-flooding-protection",
            "--disable-extensions-http-throttling",
            "--disable-field-trial-config",
            "--disable-back-forward-cache"
    );

    // 通用Chrome参数
    public static final List<String> COMMON_ARGS = Arrays.asList(
            "--disable-cookie-encryption",
            "--disable-sync",
            "--log-level=2",
            "--enable-logging=stderr",
            "--remote-debugging-port=" + DEBUG_PORT,
            "--allow-legacy-extension-manifests",
            "--allow-pre-commit-input",
            "--disable-blink-features=AutomationControlled",
            "--install-autogenerated-theme=0,0,0",
            "--no-pings",
            "--no-first-run",
            "--no-default-browser-check",
            "--no-startup-window",
            "--disable-default-apps",
            "--ash-no-nudges",
            "--disable-infobars",
            "--disable-search-engine-choice-screen",
            "--disable-session-crashed-bubble",
            "--simulate-outdated-no-au=\"Tue, 31 Dec 2099 23:59:59 GMT\"",
            "--hide-crash-restore-bubble",
            "--suppress-message-center-popups",
            "--disable-client-side-phishing-detection",
            "--disable-domain-reliability",
            "--disable-component-update",
            "--disable-datasaver-prompt",
            "--disable-hang-monitor",
            "--disable-session-crashed-bubble",
            "--disable-speech-synthesis-api",
            "--disable-speech-api",
            "--disable-print-preview",
            "--safebrowsing-disable-auto-update",
            "--deny-permission-prompts",
            "--disable-external-intent-requests",
            "--disable-notifications",
            "--disable-desktop-notifications",
            "--noerrdialogs",
            "--disable-popup-blocking",
            "--disable-prompt-on-repost",
            "--silent-debugger-extension-api",
            "--block-new-web-contents",
            "--metrics-recording-only",
            "--disable-breakpad"
    );

    // 私有构造函数防止实例化
    private ChromeConfig() {}

    // 获取所有参数组合
    public static List<String> getAllArgs(boolean headless, boolean docker, boolean disableSecurity) {
        List<String> args = new java.util.ArrayList<>(COMMON_ARGS);
        args.addAll(DETERMINISTIC_RENDERING_ARGS);
        if (headless) args.addAll(HEADLESS_ARGS);
        if (docker) args.addAll(DOCKER_ARGS);
        if (disableSecurity) args.addAll(DISABLE_SECURITY_ARGS);
        args.add("--disable-features=" + String.join(",", DISABLED_COMPONENTS));
        return args;
    }
}
